name: .NET Core Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
          RUNTIME: win-x64
        - os: ubuntu-latest
          RUNTIME: linux-x64
        - os: macos-latest
          RUNTIME: osx-x64
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish -r ${{matrix.RUNTIME}} -c Release -p:PublishSingleFile=true
    - uses: actions/upload-artifact@master
      with:
        name: WebWindow-ViewModelExample
        path: WebWindows.ViewModelExample/bin/Release/netcoreapp3.0/${{matrix.RUNTIME}}/publish